## Lecture 3 - Introduction to Numpy

### Basics of using [NumPy](https://numpy.org/doc/stable/).
Numpy is one the main packages in Python for scientific computation and is a must for data science and machine learning. Not everything done in Python needs it though, so the modules are not _built-in_. We must import Numpy into our Python session.

Later in the lesson, we will also want to create some visuals &ndash; plots. For this, we must import PyPlot, which is our second import line.

> If not working in the cloud, you might have to install the packages the very first time you try import them. To do so, you may use one of the following terminal command from your home directory.

`python -m pip install <package name>` (Windows)

`sudo pip install <package name>` (Linux or Unix-based)

In [2]:
import numpy as np
import matplotlib.pyplot as plt

The main object that you work with in Numpy is an `ndarray`, which is constructed from a list using the command `np.array(the_list)`. 

If the items in the list are numerical &ndash; `int` or `float` &ndash; then the `ndarray` object is much like a vector. In this case, it is a _\tensor of order 1_ (confusingly, may sometimes read this as ``rank 1 tensor'', though this is not rank in the usual sense). For any integer $d\ge 1$, you can have a Numpy array that is a tensor of order $d$. You may also read it described as a "$d$-dimensional array."

One of the attributes of a Numpy array is its _shape_. When it is order 1, the shape has the form `(n,)`, where `n` is the number of items (coordinates) in that vector.

In [5]:
v = np.array([-1,1,1])

# Here is the shape of v
v.shape

(3,)

In [6]:
type(v)

numpy.ndarray

If the input to `np.array()` is a list of lists, and each "inside" list has numeric type items, then the resulting `ndarray` is a rank 2 tensor &ndash; a matrix. (The inside lists must all have the same length.)
If `A` is such an object, then to refer to the entry in row `i` and column `j`, use `A[i,j]`.

Below, we make another vector, `w`, and two matrices (rank 2 tensors) `A` and `P`. Check out how we can do linear combinations as in linear algebra. (Notice below how `2*w` gives you the scalar 2 times the vector `w`.)

In [6]:
w = np.array([0.5,0,1.1])
A = np.array([[5/6,7/6,-1/3],[2/3,4/3,-2/3],[1/6,-1/6,1/3]])
P = np.array([[1,1,-1],[1,0,1],[0,1,1]])

In [8]:
v + 2*w

array([0. , 1. , 3.2])

In [9]:
A+P

array([[ 1.83333333,  2.16666667, -1.33333333],
       [ 1.66666667,  1.33333333,  0.33333333],
       [ 0.16666667,  0.83333333,  1.33333333]])

In [12]:
# the shape of a rank 2 tensor == (m,n) when it is an m x n matrix
M = np.array([[2,5,8],[2,6,10]])

M.shape

(2, 3)

> Programming note (to be aware): If you put integers into a numpy array, it will give them integer data types, "int64"; decimal numbers are stored as a "float64". Each array will only have one data type (unlike lists). If you combine them (e.g., adding them) and one array has ints but the other has floats, or if you divide by integer, NumPy will convert to floats.

In [10]:
type(P[0,1]), type(A[0,1])

(numpy.int64, numpy.float64)

Multiplying matrices and multiplying a matrix times a vector are done easily. To multiply matrices, use the `@` symbol (in recent versions of Python, this replaces `np.matmul()`). This will work for a matrix times a vector too. However, for matrices and vectors (not higher rank tensors) you could also use `np.dot()`. This performs the dot product on each row (if a matrix is given first).

In [13]:
M@P

array([[ 7, 10, 11],
       [ 8, 12, 14]])

In [14]:
A@v

array([5.55111512e-17, 0.00000000e+00, 0.00000000e+00])

In [15]:
np.dot(A, v)

array([5.55111512e-17, 0.00000000e+00, 0.00000000e+00])

> Note that, when we computed `A` times `v`, the first component was not equal to exactly 0. This is a consequence of rounding errors. (Notice the difference below, where it should be that both the first and second computation equal to 5/6.)

In [ ]:
(A[0][2]+A[0][1]).astype(str), A[0][0].astype(str)

('0.8333333333333335', '0.8333333333333334')

> Numpy has a lot of [Linear Algebra](https://numpy.org/doc/stable/reference/routines.linalg.html#module-numpy.linalg) operations built in. Here is the norm of a vector, `np.linalg.norm()`, and matrix inverse, `np.linalg.inv()`. The to get the transpose, use `.T` after the matrix. (For a vector, you need to convert it to a one-row matrix first.) 

In [ ]:
np.linalg.norm(v), np.sqrt(3)

(1.7320508075688772, 1.7320508075688772)

In [17]:
np.linalg.inv(P)

array([[ 0.33333333,  0.66666667, -0.33333333],
       [ 0.33333333, -0.33333333,  0.66666667],
       [-0.33333333,  0.33333333,  0.33333333]])

In [24]:
# transpose of matrix and of a vector
print(P.T)

print( v.reshape(1,3).T )  # could also have .reshape(1,-1) here if you don't know the length of the vector

[[ 1  1  0]
 [ 1  0  1]
 [-1  1  1]]
[[-1]
 [ 1]
 [ 1]]


#### More on indexing matrices
Often, you want to get all items in one row, or all items in one column, of a given matrix `A`. For this, you can use slicing, either `A[i, :]` (for row i) or `A[:, j]` (for column j). 
> For the row, you could also just type `A[i]` (getting the i$^{th}$ list in this list of lists). But you need slicing for the column.

In [26]:
print(A)

A[:,1]

[[ 0.83333333  1.16666667 -0.33333333]
 [ 0.66666667  1.33333333 -0.66666667]
 [ 0.16666667 -0.16666667  0.33333333]]


array([ 1.16666667,  1.33333333, -0.16666667])

You can also get a submatrix of `A`.

In [27]:
A[1:,:2]

array([[ 0.66666667,  1.33333333],
       [ 0.16666667, -0.16666667]])

#### Other arithmetic operations with tensors
Why didn't the developers just have `M*A` be interpreted as matrix multiplication of `M` and `A`? While element-wise multiplication doesn't get discussed much in a first linear algebra course, it is often _very_ useful in scientific computing and Numpy handles it very well.
> The operation `*` carries out element-wise multiplication. That is, the tensors being multiplied **should have the same shape** and items in the same position are multiplied.

This means that a power of a square matrix (using `**`) will take element-wise powers.

In [30]:
print(v*w)
print(A*P)

[-0.5  0.   1.1]
[[ 0.83333333  1.16666667  0.33333333]
 [ 0.66666667  0.         -0.66666667]
 [ 0.         -0.16666667  0.33333333]]


In [31]:
P**2

array([[1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

You can also easily add  one number to every entry.

In [32]:
Q = P + 2
Q

array([[3, 3, 1],
       [3, 2, 3],
       [2, 3, 3]])

In [33]:
Q - P

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

#### Reduction

In [37]:
print(M)
print(M.sum())

print(M.sum(axis=0))
print(M.sum(axis=1))

[[ 2  5  8]
 [ 2  6 10]]
33
[ 4 11 18]
[15 18]


In [43]:
# quick Euclidean norm
print(w)
print( np.sqrt((w**2).sum()), np.linalg.norm(w) )

[0.5 0.  1.1]
1.2083045973594573 1.2083045973594573


In [47]:
# Max along an axis
print(M.max(axis=0))
# Mean along an axis
print(M.mean(axis=0))

[ 2  6 10]
[2.  5.5 9. ]


#### All zero matrix and the identity matrix
Since they are needed so often, there is a function to construct a tensor filled with zeros of your chosen size and also a function to construct an $n\times n$ identity matrix.

In [49]:
zerovector = np.zeros(5)
zeromatrix = np.zeros((4,4))
print(zerovector, ',')
print(zeromatrix)

[0. 0. 0. 0. 0.] ,
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [52]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
# quickly make a diagonal matrix
np.diag([3,2,1])

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 1]])

In [62]:
m = 200
DistM = np.random.uniform(0, 2.5, size=(m,m))*np.tri(m)
Delt = np.diag(DistM.diagonal())
DistM -= Delt
# Which entry is largest? 

In [69]:
import time

In [73]:
start = time.time()
mx = DistM.argmax()
i,j = mx//m, mx%m
end = time.time()
nanoseconds = (end - start)*1e9
print(f"Ran in {nanoseconds} nanoseconds.")

Ran in 0.0 nanoseconds.


In [74]:
print(mx, i, j)

28682 143 82


In [75]:
start = time.time()
mx = 0
mi, mj = -1, -1
for i in range(200):
  for j in range(200):
    if DistM[i,j] > mx:
      mx = DistM[i,j]
      mi = i
      mj = j
end = time.time()
microseconds = (end - start)*1e6
print(f"Ran in {microseconds} microseconds.")


Ran in 8028.0303955078125 microseconds.
